name: Generate Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle CLI
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Generate Gradle wrapper (8.0.2) from app module
        working-directory: app
        run: gradle wrapper --gradle-version 8.0.2 --distribution-type=all

      - name: Move wrapper to project root
        run: |
          mv app/gradlew .
          mv app/gradlew.bat .
          mkdir -p gradle/wrapper
          mv app/gradle/wrapper/* gradle/wrapper/

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Commit and push new wrapper
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add gradlew gradlew.bat gradle/wrapper
          git commit -m "Regenerate Gradle wrapper 8.0.2"
          git push
